### ISSUE TITLE
Plugin fails in ST3 4143

### ISSUE THREAD

**Issue by reagle** [shagabutdinov/sublime-snippet-manager#3]
```
reloading plugin SublimeEnhancedUtilitiesSet.commands
Some dependencies has not been imported for Utilities package; some utilities functionality will not be availiable
reloading plugin SublimeEnhancedUtilitiesSet.go
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "go in /Users/reagle/Library/Application Support/Sublime Text 3/Installed Packages/SublimeEnhancedUtilitiesSet.sublime-package", line 2, in <module>
ImportError: No module named 'Expression'
```

**Comment by shagabutdinov** [comment]
Install `sublime-expression`.

**Comment by reagle** [comment]
Should this then be a dependency in the package control?

**Comment by shagabutdinov** [comment]
You can open PR to https://github.com/shagabutdinov/sublime-utilities repo if you want. When I did those plugins there was no way to specify dependencies in packages.
